language: java
sudo: false

jdk:
  - oraclejdk8

install: true
script: ./travis.sh

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
  webhooks:
    - secure: "doJkMogfoBInm5tAXKgFOZo10huabCaLFFteej+UL0kGBJiadE9wMLcCg753yvdS1ZoFAYlL0Ry+4tq2cmDlsmJjjc3z/gWlhYzDPuIgSYVsO6YVkLuuhYLfETowuwwtJvbaumQfS4wPGBmmLJe7sD/aHiJszc8EL4j3dJgXlRujFzn6Rw1QIPB06AyRtyjzpUmlHEt1wjFsbYj5hzEtSs7ymt0K6unSO6GTOUncQtJqEhll7/ZLPtt7s7IokxEFTqMSkWknlHS553lKkebIMoNkskKia8yis8BLSFRueAh6chFgIOiNXApaCipP+l6rj6uLfSr3vYoNEvJVEUP9InEHzO8ZJ8WynMRsd1A1sbrJSjhZKpw3gaivVm7emzH5JHWrDDQkHVEyCbRtOw3Me0qba1hP4Rs3bp3YINhvdeJmylaUW5hjw5QWseCMmo+3kQExNPUVuN7bYTrgojZt9p9h/4tVSsW1QcvjOTz90zFRAb3lAr7KHGCeJ3LbTV/i95FZOWjp6eom8UtmbonEPDpjBXtXHsi31Lv+iKk+2k0vm0l17tQXSpkpOmiq2dSDwUvbk4y5veBzRfMqZgpg0O5FG1OtV9ajqNxazMcUgGnu/2frSF8qC6ALp/uUMSZ7RaXyeG3o9Th7MCkPMtnHl6rJJUrCgHO1yJeb8Nbo15o="
  on_start: always

addons:
  apt:
    packages:
      # upgrade java 8 as the default version 1.8.0_31 prevents from compiling sources
      # https://github.com/travis-ci/travis-ci/issues/4042
      - oracle-java8-installer
