language: java
sudo: false

jdk:
  - oraclejdk8

install: true
script: ./travis.sh

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
  webhooks:
    - secure: "RjeHqaA82uYjueBl4+t3iSSabxyYo5u/baox97A1N8vUrvFPorANCX3waS8EWghACG1abCs6fLa8sKex8uLCzEQLfI5//L64a3gtIhZ4ChGkDa4+j0AGY80e0Niui3Ij/yM+wpUzERJZiMqFR+SI/XSY8m7K3tiQkb/Qfh5dMULoyf6kLWcWhJA8QXwaItwliEafpZ9vFMOClHKkO3T5P8ZpAgUJnOSYgqeDPE7hik+K+zKh6EOEQHj/ucAaueSumY+oxRxFRmAeIGkdeY7iAlke8Xzto0EsOC6SYrzbHm2zLQ1PW7d8ZkKrWtWX//9QXeRA4DqXhAf0u/PcnglkuAAIpuyTZ2RPn3xOxE6SFBpvSyQZZTBoFw5xGEoRPKFPCr1/E7Nini4ROmzi0P7oDkm6zPLoqBnyjUkjBUh720xniNACOlBHkzTl59PuLl1KWRl5njlYeGWYi3P2UIweVnMgea16cqKFFTFxMYZj3QJB8rU5a46kZ56J2B7DIq29eTrjEVFIQhj2TmORUgPN3peNIpI+MYD98ixMd4fMwHrw0Es5q6cpXjV14SaDAP0zxfuED++wP5phCKvaqcKZZ5Y6H3xR/w1nC8tt7t6AqihWg2dDjJxMy+hr4h/l0+EGLsDRedRDxO0i93AlvqynLM/A/7A9wuIsTkAhX6T9dLo="

addons:
  apt:
    packages:
      # upgrade java 8 as the default version 1.8.0_31 prevents from compiling sources
      # https://github.com/travis-ci/travis-ci/issues/4042
      - oracle-java8-installer
