language: java
sudo: false

jdk:
  - oraclejdk8

install: true
script: ./travis.sh

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
  webhooks:
    - secure: "b6aNBoqDpA+mBY/sV4UqglIWczFgwSUdojb5IfvUfqVwf1GRfE8TXjhPn+H3pxtrHPDPEg5Jmbko51lKYZZGs9Sg0R+kVuTEh9mwT+6pGrXv9/HEOa1ftr6CcdkcVBurwJMmAOOYnKIS83hnlMTeVYct6CHV7QlJvy+rktclipPEtlCkAM7K1xZeR/Ts6wUGsE1JfPyOSynbue26gJID4bS2gAIFRlyFGPKxf+rPPAu8Mx351kcNfADOKGtFI2rBlcea4nCveYcUmd0R9fnKafpATZJFcxx4Boy73qbNAaJGtqdEE/8yWRlqqmEd6HmaTWyZV50o7a5wvwkbAx7W+8eTrXbhjPmRmrZlfjqPegWWnYywP2eCaYOlmOiSaN7U7Kl8DW7FhOsaspenk2E6bEVjGlu5r8KB/BpHtX7P9YKUPVf3f3t0Nfd1s7uaP09V1xdlvMKN6URodQDmAek+2ZRFCVHdSMtQ8k5XyHw+prvQehYgY3Rbu3Bwb9t9cYyjFt2e4TOXOVBgnuR0OoMX7jhSF7Qsgc3N9Y4rRHG2Bx8f3o7134qdua/mUmh7LYThI3sjVGfI2FH91bkkwlv08wQs5WkfVOtJ9W2x66qIWaqll/ztMpawvTUC+cDehVg7IksQbl6u9b9oFtn9cZsc3cZJg9hWURAKgk/XWus8f2s="
  on_start: always

addons:
  apt:
    packages:
      # upgrade java 8 as the default version 1.8.0_31 prevents from compiling sources
      # https://github.com/travis-ci/travis-ci/issues/4042
      - oracle-java8-installer
